---
title: "KIND resources"
---

This is the main page for the KIND network's live documents and non-training resources. 

+ if you're looking for our core training courses, please see [our TURAS pages](https://learn.nes.nhs.scot/36783)
+ if you're looking for details of our one-off training sessions, please see the [KIND training mini-site](https://nes-dew.github.io/KIND-training/)
+ if you're looking to join the KIND Network Teams channel, [you'll find a sign-up form here](https://forms.office.com/r/WQdd6HSCEW). That channel is open to all, although mainly meant for members of the knowledge, information, and data workforce across Scotland's health, social care, and housing sectors
+ you can [join our mailing list here](https://forms.office.com/pages/responsepage.aspx?id=veDvEDCgykuAnLXmdF5JmpopIZB9ynRJnrPUHVFccipURjM2NkZJUkhGOFlQRjQxRFhVUTgwT0UwVyQlQCN0PWcu). We send out a weekly mailer summarizing the main events in the coming week, and [that's archived here too](ml_archive.qmd).  

## What's here?

### Community standards.

These documents set out simple, human, and sensible platform-specific standards that we think some of the most widely-used knowledge, information, and data tools should follow.
 
How might you use these suggestions?

+ as a way of highlighting good practice
+ as a helper when starting new projects (or new Excel documents)
+ as a lever for bringing about change, particularly trying to convince service leads that poorly-designed Excel spreadsheets are a dangerous menace
+ as a guideline for tidying up existing inconsistent/messy files
+ as a training tool when bringing new colleagues up to speed

Please take this, use it however you like, and let us know if there's anything that you'd find particularly helpful for an updated version to contain. We'll review and redraft regularly. Please [open an issue on the GitHub page](https://github.com/NES-DEW/KIND-community-standards/issues) if you have specific suggestions, otherwise contact brendan.clarke2@nhs.scot for a more general conversation about these standards.

### Sample SOPs

These are a set of sample standard operating procedures for KIND work. These are intended for sharing as a basis or guideline for your own activities. Please get in touch if you have a useful SOP that might be sharable.

### KIND FAQ

Our main frequently-asked questions document

### Book of the week

Data and summaries for our ever-popular book of the week segment

### Community meetup schedule