---
title: "Power Query week"
execute: 
  freeze: false
editor_options: 
  chunk_output_type: console
---

## Power Query week plan

We're running a network-wide [Microsoft Power Query](https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query) week between 19th and 23rd May. That’ll include a range of training sessions at all levels, opportunities for 1:1 and group project support, and presentations from users who are putting Power Query to work in health and social care.

## What's Power Query?
It's a set of data-wrangling tools in Excel/Power BI. It's designed to help you load/tidy/reshape data. It's especially exciting, because you can use it to automate some aspects of data handling, potentially saving yourself hours of manual data work. If you're currently doing data cleaning by hand in Excel, you should know about PQ.

### Training sessions

+ [Scope of the possible with Power Query](https://events.teams.microsoft.com/event/7a8ba2ad-3361-4e24-aa76-a0acce500df6@10efe0bd-a030-4bca-809c-b5e6745e499a) - 10:00-11:00 Mon 19th May 2025
+ [Power Query - a practical introduction](https://events.teams.microsoft.com/event/6551076b-5daa-4dd5-b024-4d4847136652@10efe0bd-a030-4bca-809c-b5e6745e499a) - 14:00-16:00 Tue 20th May 2025
+ [Troubleshooting Power Query](https://events.teams.microsoft.com/event/e116e8b5-c9dc-46c9-b8da-f5163ecd9361@10efe0bd-a030-4bca-809c-b5e6745e499a) - 10:00-11:00 Wed 21st May 2025
+ [Groups and summaries in Power Query](https://events.teams.microsoft.com/event/fcc480fa-f38b-4279-9a28-ef55a2dbdda4@10efe0bd-a030-4bca-809c-b5e6745e499a) - 14:30-15:30 Wed 21st May 2025
+ [An introduction to PQM](https://events.teams.microsoft.com/event/593ffb0a-fbde-44ff-b800-7af7ec73c338@10efe0bd-a030-4bca-809c-b5e6745e499a) - 11:30-12:30 Thu 22nd May 2025


### Social and project sessions
Sessions for support, and sessions showing off real Power Query projects.

+ [Heather Mcbroom (Scottish Ambulance Service) - project presentation about merging many Excel sheets](https://events.teams.microsoft.com/event/d62bc7e2-85d6-48de-994d-3651b760b8d3@10efe0bd-a030-4bca-809c-b5e6745e499a) - 13:00 Mon 19th May 2025
+ [Carla Dempster (NHS Lothian) - project presentation about completing templates using power query](https://events.teams.microsoft.com/event/99e9a599-dae5-4e7c-b2e1-9636d47b8e77@10efe0bd-a030-4bca-809c-b5e6745e499a) - 11:00 Wed 21st May 2025
+ [KIND network Power Query week: help session](https://events.teams.microsoft.com/event/9125e71e-27dd-4a5e-a352-5a7c7a31bc86@10efe0bd-a030-4bca-809c-b5e6745e499a) - 14:30 Thu 22nd May 2025
+ [Alupha Chan (NHS Tayside) - project presentation - let's stitch sheets together!](https://events.teams.microsoft.com/event/1a1a5c2a-c412-4189-bc33-ee85d7c14a09@10efe0bd-a030-4bca-809c-b5e6745e499a) - 10:00 Fri 23rd May 2025
+ [Louise McCafferty Thomson and Sarah Aitken (NHS Education for Scotland) - project presentation about data processing with Power Query](https://events.teams.microsoft.com/event/6044579c-5571-4d56-be57-6b7e83d7c4c1@10efe0bd-a030-4bca-809c-b5e6745e499a) - 11:00 Fri 23rd May 2025
+ [David Bain (NHS GGC) - project presentation about combining referral data across a large clinical service](https://events.teams.microsoft.com/event/4ff545d0-7766-4e10-ad28-7d0b6cc7b1e0@10efe0bd-a030-4bca-809c-b5e6745e499a) - 13:00 Fri 23rd May 2025
+ [David Pentland (NHS GGC) - project presentation about using PQ to extract data from planner](https://events.teams.microsoft.com/event/819c32cb-d011-489d-811c-5f3b1d0b5984@10efe0bd-a030-4bca-809c-b5e6745e499a) - 14:30 Fri 23rd May 2025