---
title: "KIND Mentoring Scheme"
date: 2024-08-22
---

:::{.callout-warning collapse=false appearance='default' icon=true}
## Draft guidance

This is currently draft guidance, may therefore contain errors and omissions, and is liable to change

:::

We run an informal mentoring scheme. It's designed to support professional development, by putting together mentors and mentees to work on a well-defined project over about 8 weeks. The scheme operates entirely by mutual consent, so participants are free to leave at any time. We think the benefits are reciprocal, with both parties gaining from the work.

## Why mentoring?

:::: {.columns}

::: {.column width='50%'}
### For mentees
+ an opportunity to get support and guidance that might not be available in your workplace 
+ an efficient way of putting skills into practice
+ build your professional network
::: 

::: {.column width='50%'}
### For mentors
+ pass on your skills and knowledge to the wider community
+ to strengthen your understanding of a topic - think of mentoring as a variant of the [Feynman method](https://www.k-state.edu/aac/success-tools/collection/Feynman_Technique.pdf) + to develop new professional skills, particularly skills relevant to more senior roles such as management, personal development, and community building 
::: 

::::

## Mentoring projects

::: {.panel-tabset}
### Good project ideas
+ **help me turn some R code into a package** - specific and achievable
+ **support me through a first literature review** - sharing expertise
+ **I've just done a course on x, but need some support putting x to work in y** - supporting areas not well-covered by other means

### Bad project ideas
+ **teach me how to code** - open-ended projects aren't a good fit for an 8-week mentoring arrangement
+ **advise our organisation on x** - mentoring isn't consultancy
+ **I need someone to encourage me to work harder** - mentoring isn't cheerleading
+ **my spreadsheet is broken** - focal requests for assistance would be better asked on the KIND network
:::

## How it works 

:::: {.columns}

::: {.column width='60%'}
```{mermaid}
%%| fig-width: 6
%%| fig-height: 8

graph TD;

request["Mentee sends a project outline"] --> mentorfinds["Mentor finds a suitable project outline"]

mentorfinds --> email["Both discuss by email"]

email --> meeting["Informal meeting to set goals and expectations"]

meeting -->  contract["Sign contract"]

contract --> complete["Complete the mentoring project"]

complete --> present["Present the project at the mmmmm"]

```
:::

::: {.column width='40%'}
1. a mentee puts a request on the KIND Teams channel by filling in the [new project form](https://forms.office.com/e/AUCcHB4ySj)

1. a mentor [sees the request on the Teams channel](https://teams.microsoft.com/l/channel/19%3A0708d3664e064dd3a0dbbe3079817283%40thread.tacv2/Mentoring?groupId=106d08f3-9026-40e2-b3c7-87cd87304d58&tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a), and [expressed interest in mentoring](https://forms.office.com/e/01bdi52YHB))

1. we put the mentee and mentor in touch by email to discuss the project

1. mentor and mentee meet to agree a broad outline for their mentoring arrangement

1. both mentor and mentee [sign a mutua-consent contract]((https://forms.office.com/e/ik4fpth04B))

1. we help and support them through the duration of the scheme. [Either party can withdraw at any time](https://forms.office.com/e/9mDyGFVzB1) without fault

1. we invite mentors and mentees to come and present their experiences at the monthly mentoring meetup
:::

::::

## Key documents

+ [new mentoring request form](https://forms.office.com/e/AUCcHB4ySj) - use this to propose a new project
+ [potential mentor form](https://forms.office.com/e/01bdi52YHB) - use this to express interest in mentoring a project
+ [contract form](https://forms.office.com/e/ik4fpth04B) - use this to agree a new mentoring relationship (see [a sample contract](src/KIND_mentoring_sample_contract.pdf))
+ [withdrawal form](https://forms.office.com/e/9mDyGFVzB1) - use this to end a mentoring relationship

## What makes a good mentoring project?

+ successful projects are generally short and simple
  + short meaning they can generally be finished off during the 8 week mentoring scheme
  + simple meaning they don't depend on a lot of new infrastructure, require organisational change, or need an mentor to gain an unrealistic range of new skills
+ successful project proposals should therefore be short and precise
  + what are you trying to do?
  + how are you trying to do it?
  + which barrier(s) do you have in place?
  + what do you need a mentor to do?
+ successful projects aren't about cheerleading
  + we'd expect mentors to provide largely technical advice: "have you considered using x"
  + we do not expect mentors to provide detailed technical training
  + we specifically preclude mentors giving detailed technical advice regarding systems. Mentors are not consultants.

## What might I do instead?
If your project doesn't fit this scheme, consider:

+ asking a question [on the KIND teams channel](https://teams.microsoft.com/l/channel/19%3AQZ7-PbFVcziG2piHLt1_ifey3I2cwFL0yBuTSS8vVao1%40thread.tacv2/General?groupId=106d08f3-9026-40e2-b3c7-87cd87304d58&tenantId=10efe0bd-a030-4bca-809c-b5e6745e499a)
+ completing one of our [training courses](https://learn.nes.nhs.scot/36791) on a topic, particularly if you're struggling to put your request into specific language
+ presenting your query/issue in one of the open [KIND community meetup sessions](kind_cms.qmd)