---
title: "KIND unconference 2024"
execute: 
  freeze: false
---

## Schedule

```{=html}

<table>
  <tr>
  <th>Start</th>
  <th colspan="2"><center>Topic</center></th>
  </tr>
  
  <tr>
    <td>09:30</td><td colspan="2"><center><a href="https://events.teams.microsoft.com/event/8851dfe1-6c9d-4fa9-9ab3-89a56b6ac7df@10efe0bd-a030-4bca-809c-b5e6745e499a">Introduction and chat</a></center></td>
    </tr>
    
    <tr>
    <td colspan="3"><center><b>Show-off session: short project presentations</b></center></td>
    </tr>
    <tr>
    <td>09:40</td>
    <td><a href="https://events.teams.microsoft.com/event/83d06869-69f4-42da-8491-4399ea1ac319@10efe0bd-a030-4bca-809c-b5e6745e499a">Functions from Posit Academy (Sophie Mackintosh)</a></td>
    <td><a href="https://events.teams.microsoft.com/event/3497b120-6840-497e-95d8-ae8e518c8bdc@10efe0bd-a030-4bca-809c-b5e6745e499a">Between Excel and R - preparing data for safe haven transfer (Alupha Chan)</a></td>
    </tr>
    <tr>
    <td>10:00</td>
    <td><a href="https://events.teams.microsoft.com/event/60ec5eaf-bb53-470d-bcaf-aae6efdf1031@10efe0bd-a030-4bca-809c-b5e6745e499a">Data sharing with pins (Catriona Scott)</a></td>
    <td><a href="https://events.teams.microsoft.com/event/57aa9377-7a50-410b-af44-04e7517d33f1@10efe0bd-a030-4bca-809c-b5e6745e499a">QI data storytelling (Emily Waite, Daniel Gunn, Penny Fairbairn)</a></td>
    </tr>
    <tr>
    <td colspan="3"><center><b>Theme discussions</b></center></td>
    </tr>
    <tr>
        <td>10:20</td><td><a href="https://events.teams.microsoft.com/event/70570392-150f-4be9-a5a0-0299bd335831@10efe0bd-a030-4bca-809c-b5e6745e499a">"high demand for support from the users, far more than I expected" (Sarah Downie)</a> </td>
        <td><a href="https://events.teams.microsoft.com/event/341030de-d4e0-4628-9372-32da0d5b06fa@10efe0bd-a030-4bca-809c-b5e6745e499a">"if it doesn't help your prospects then what's the point of it" - professional registration as somewhere between pointless money-pit and vital route to becoming a proper career (Carla Dempster and Sophie Mackintosh)
</td>
    </tr>
    <tr>
        <td>11:00</td><td colspan="2"><center><b>Break</b></center></td>
    </tr>
        <tr>
    <td colspan="3"><center><b>Theme discussions</b></center></td>
    </tr>
    <tr>
        <td>11:20-12:00</td><td><a href="https://events.teams.microsoft.com/event/126f44fb-ff7f-418f-95df-f98e2175c495@10efe0bd-a030-4bca-809c-b5e6745e499a">"some sort of lessons learned from setting up new tech" - what have we learned about new tech, what do we wish we'd known beforehand, and what information should we (have) capture(d) (Julian Augley and Zena Trendell)</a></td>
        <td><a href="https://events.teams.microsoft.com/event/ff656b9c-e123-4047-8020-4d84d185dea4@10efe0bd-a030-4bca-809c-b5e6745e499a">"Theme discussion: "we have access to an Aston Martin and we are using it for the school run" - making the case for what we already have, making the case for exploiting available capabilities, realising benefits, and overcoming resistance to change
(Katy Mccalister, Brian Orpin, George Maldonado)</td>
    </tr>
    <tr>
        <td>12:00</td><td colspan="2"><center><a href="https://events.teams.microsoft.com/event/d8cb4cf4-4dff-4856-9a2b-fa7fab0fbe9f@10efe0bd-a030-4bca-809c-b5e6745e499a">"what do you want out of the network during 2025</b>": KIND network direction of travel</a></center></td>
    </tr>

    <tr>
        <td>12:40</td><td colspan="2"><center><b>Lunch</b></center></td>
    </tr>

    <tr>
    <td colspan="3"><center><b>Theme discussions</b></center></td>
    </tr>
    <tr>
        <td>13:20</td><td colspan="2"><a href="https://events.teams.microsoft.com/event/1e92d2bf-17f8-4668-bb07-ea999d4936a1@10efe0bd-a030-4bca-809c-b5e6745e499a">"you said X first, and that suits, so we'll stick with X" - doing things fast vs doing them right, and communicating the difference to colleagues/stakeholders etc (Sophie Mackintosh and Catriona Scott)</a></td>
    </tr>
    <tr>
    <td colspan="3"><center><b>Show-off session: short project presentations</b></center></td>
    </tr>
  
    <tr>
    <td>14:00</td>
    <td><a href="https://events.teams.microsoft.com/event/dc1f0591-0e27-462d-9604-19fc03cdf5a5@10efe0bd-a030-4bca-809c-b5e6745e499a">R project templates for the Scottish Liver Transplant Unit Data Team (Stephen Mcgill)</a></td>
    <td><a href="https://events.teams.microsoft.com/event/41be4a29-5e28-4268-8a40-441dddcfc780@10efe0bd-a030-4bca-809c-b5e6745e499a">From Excel/Word reporting, to R Markdown (Keir Robertson)</a>
    </td>
    </tr>
    
    <tr>
    <td>14:20</td>
    <td colspan="2"><center>Free for last-minute presentations</center></td>
    </tr>
    
    <tr>
    <td colspan="3"><center><b>Theme discussions</b></center></td>
    </tr>
    
    <tr>
    <td>14:40</td>
    <td colspan="2"><a href="https://events.teams.microsoft.com/event/11882783-d1ac-49d0-a1a8-bc90428afa71@10efe0bd-a030-4bca-809c-b5e6745e499a">Theme discussion: “'we weren’t trained' and 'we’re not interested.'” (Brendan Clarke)</a> </td>
    </tr>
    
    <tr>
    <td>15:20</td>
    <td colspan="2"><center><a href="https://events.teams.microsoft.com/event/f918dff8-97b0-479a-9fb5-56a09cdf3ad0@10efe0bd-a030-4bca-809c-b5e6745e499a">Wrap-up: free chat, ambitions, scheming, and complaints</a></center></td>
    </tr>
  
    <tr>
    <td>15:40ish</td>
    <td colspan="2"><center><b>Finish</b></center></td>
    </tr>
    
    
    
</table>
```

## Theme discussions

We'll be running short discussion sessions on the following topics:

-   "*some sort of lessons learned from setting up new tech*" - what have we learned about new tech, what do we wish we'd known beforehand, and what information should we (have) capture(d)

-   "*we have access to an Aston Martin and we are using it for the school run*" - making the case for what we already have, making the case for exploiting available capabilities, realising benefits, and overcoming resistance to change

-   "*high demand for support from the users, far more than I expected*" - knowledge sharing, dealing with support and training needs, keeping yourself/everyone else current, and trying to think sensibly about different needs and different ways of supporting those needs

-   "*proceeding until apprehended*" - some people seek permission, others forgiveness. Balancing getting things done with professional obligations in a climate of murky guidance

-   "*you said X first, and that suits, so we'll stick with X*" - doing things fast vs doing them right, and communicating the difference to colleagues/stakeholders etc

-   "*'we weren't trained' and 'we're not interested.'* " skills mapping, writing JDs to suit actual needs, and developing some understanding of how skills and careers can be better fitted together

-   "*if it doesn't help your prospects then what's the point of it*" - professional registration as somewhere between pointless money-pit and vital route to becoming a proper career?
